# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.135.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Web Cryptography API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
aes.workspace = true
aes-gcm = "0.10"
aes-kw = { version = "0.2.1", features = ["alloc"] }
base64.workspace = true
cbc.workspace = true
const-oid = "0.9.0"
ctr = "0.9.1"
# https://github.com/dalek-cryptography/curve25519-dalek/pull/397
curve25519-dalek = "2.1.3"
deno_core.workspace = true
deno_web.workspace = true
elliptic-curve = { version = "0.12.1", features = ["std", "pem"] }
num-traits = "0.2.14"
once_cell.workspace = true
p256 = { version = "0.11.1", features = ["ecdh"] }
p384 = "0.11.1"
rand.workspace = true
ring = { workspace = true, features = ["std"] }
rsa.workspace = true
sec1 = "0.3.0"
serde.workspace = true
serde_bytes.workspace = true
sha1 = { version = "0.10.5", features = ["oid"] }
sha2.workspace = true
signature.workspace = true
spki = "0.6.0"
tokio.workspace = true
uuid.workspace = true
# https://github.com/dalek-cryptography/x25519-dalek/pull/89
x25519-dalek = "2.0.0-pre.1"
